### ISSUE TITLE
Deprecation warning when running on PHP 8.2

### ISSUE THREAD

**Issue by spriebsch** [theseer/Autoload#104]
When I run phpab on PHP 8.2, I get a deprecation warning:

[spriebsch@spriebsch master-coder]$ php -v
PHP 8.2.2 (cli) (built: Jan 31 2023 13:31:55) (NTS gcc x86_64)
Copyright (c) The PHP Group
Zend Engine v4.2.2, Copyright (c) Zend Technologies
    with Xdebug v3.2.0, Copyright (c) 2002-2022, by Derick Rethans

[spriebsch@spriebsch master-coder]$ tools/phpab -o src/autoload.php src
PHP Deprecated:  Creation of dynamic property TheSeer\Autoload\CLI::$outputOption is deprecated in phar:///home/spriebsch/thephpcc/master-coder/tools/phpab/phpab/CLI.php on line 362
PHP Stack trace:
PHP   1. {main}() /home/spriebsch/thephpcc/master-coder/tools/phpab:0
PHP   2. TheSeer\Autoload\CLI->run() /home/spriebsch/thephpcc/master-coder/tools/phpab:157
PHP   3. TheSeer\Autoload\CLI->setupInput() phar:///home/spriebsch/thephpcc/master-coder/tools/phpab/phpab/CLI.php:82
PHP Deprecated:  Creation of dynamic property TheSeer\Autoload\CLI::$lintOption is deprecated in phar:///home/spriebsch/thephpcc/master-coder/tools/phpab/phpab/CLI.php on line 472
PHP Stack trace:
PHP   1. {main}() /home/spriebsch/thephpcc/master-coder/tools/phpab:0
PHP   2. TheSeer\Autoload\CLI->run() /home/spriebsch/thephpcc/master-coder/tools/phpab:157
PHP   3. TheSeer\Autoload\CLI->setupInput() phar:///home/spriebsch/thephpcc/master-coder/tools/phpab/phpab/CLI.php:82
phpab 1.27.1 - Copyright (C) 2009 - 2023 by Arne Blankerts and Contributors

Scanning directory src

Autoload file src/autoload.php generated.

**Comment by theseer** [comment]
Fixed in [1.27.2.](https://github.com/theseer/Autoload/releases/tag/1.27.2)

**Comment by spriebsch** [comment]
That was super quick, thank you.
