### ISSUE TITLE
Exclude directory

### ISSUE THREAD

**Issue by echodreamz** [theseer/Autoload#113]
Is there a way I am missing to exclude an entire directory and it's contents?

I have tried...

`
-e "folder/*"
`

However, the items in this folder are still added to the output. I am using Windows.

Thanks you and great project!

**Comment by theseer** [comment]
I don't use windows, so this answer may be off, but I'd bet that's a shell problem: You need to use single quotes `'` to not have it resolve the`*` before passing it into phpab.

**Comment by theseer** [comment]
Additionally, the match operation is performed on the actual path, before it's added to the map (or skipped). So it is unlikely that `folder/*` will ever match. Try ``*/folder/*'`.

**Comment by theseer** [comment]
No Feedback provided.
