### ISSUE TITLE
Trait sorted after using class when --static is used

### ISSUE THREAD

**Issue by sebastianbergmann** [theseer/Autoload#65]
DbUnit 2.0, bundled with PHPUnit >= 5.0.1, has

```php
trait PHPUnit_Extensions_Database_TestCase_Trait
{
    // ...
}
```
and
```php
abstract class PHPUnit_Extensions_Database_TestCase extends PHPUnit_Framework_TestCase
{
    use PHPUnit_Extensions_Database_TestCase_Trait;
}
```
for which PHPAB generates
```php
require 'phar://phpunit-5.0.1.phar' . '/phar/dbunit/Extensions/Database/TestCase.php';
require 'phar://phpunit-5.0.1.phar' . '/phar/dbunit/Extensions/Database/TestCaseTrait.php';
```
which means that the source of the trait is loaded after the source of a class that is using it. This leads to the problem described in https://github.com/sebastianbergmann/phpunit/issues/1887

**Comment by theseer** [comment]
This bug only occurs when in case insensitive mode. Please use --nolower until this is fixed.
