### ISSUE TITLE
Add support for Composer's autolaoder and adding autoloading in code

### ISSUE THREAD

**Issue by filips123** [theseer/Autoload#82]
Add support to use Composer's autoloader to PHAR file or somehow make class `Composer\Autoload\ClassLoader` available.

Also, add support for adding autoloading in code (https://getcomposer.org/apidoc/1.3.0/Composer/Autoload/ClassLoader.html). This is currently not possible because `Composer\Autoload\ClassLoader`is not available.

For example:

```php
$loader = new \Composer\Autoload\ClassLoader();

// register classes with namespaces
$loader->add('Symfony\Component', __DIR__.'/component');
$loader->add('Symfony',           __DIR__.'/framework');

// activate the autoloader
$loader->register();

// to enable searching the include path (eg. for PEAR packages)
$loader->setUseIncludePath(true);
```

If including Composer autoloader is not possible, you could make your own class with that name that support those things.

**Comment by theseer** [comment]
I don't understand the motivation for this?

The composer autoloader is superfluous if `phpab` is used. And they can easily co-exist, as both use spl_autoload_register.

So, to what end would this be useful?

**Comment by filips123** [comment]
I want to add multiple things to autoloader, but if this could be done with spl_autoload_register it is OK.

**Comment by theseer** [comment]
You do realize that `phpab` generates a static classmap based autoloader, right? There is conceptually no way to add classes, paths or namespaces to it after the fact.

You are of course free to also use Composers autoloader or any other custom autoload mechanism for additional classes, interfaces or traits.

They all get stacked via [spl_autoload_register](http://php.net/manual/de/function.spl-autoload-register.php). The only thing you have to keep in mind is the correct order.
