### ISSUE TITLE
`__halt_compiler` detection

### ISSUE THREAD

**Issue by sudomabider** [theseer/Autoload#88]
PSR12 wants [all keywords](https://www.php.net/manual/en/reserved.keywords.php) to be lower case which includes `__halt_compiler()`. `phpab` checks for an exact match of the uppercase version in the template:
```php
if (strpos($code, '__HALT_COMPILER();') === FALSE)
```

While not a deal breaker, the warning is annoying.

Can we perhaps make this check for lower case as well?

**Comment by theseer** [comment]
We should probably make it even case insensitive.

**Comment by sudomabider** [comment]
After some more investigation it turns out `__halt_compiler()` doesn't work at all. Only `__HALT_COMPILER()` or `__halt_compiler ()` (notice the space before the parentheses) works. This is so weird...but apparently this has been the case for years.

With that, I think there's nothing to do here. Feel free to close.

**Comment by theseer** [comment]
That's even inconsistent to the documentation. Are you sure?

**Comment by theseer** [comment]
Actually, in the context of PHAR it's documented as uppercase:

https://www.php.net/manual/de/phar.fileformat.stub.php

**Comment by sudomabider** [comment]
yeah it's confusing...the [function reference](https://www.php.net/manual/en/function.halt-compiler.php) has it in lowercase and no space in between which is the one that doesn't work. `php-cs-fixer` ran into this issue years ago: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/754

The fact that `__halt_compiler ()` with a space in between works just makes it even weirder...anyway I think `phpab` checking for `__HALT_COMPILER()` is good.

**Comment by theseer** [comment]
Thanks for the investigation :)
I'll try to get somebody from php interals to comment and i'll update this in case there's anything to be added.

Thanks for your time!

**Comment by theseer** [comment]
Got confirmation from Nikita: `__halt_compiler` is the token. The issue is that `phar` only supports the upper-case variant.

Not sure if that would qualify as a bug in the `phar`-extension, but that's how things are atm :)
