### ISSUE TITLE
Functions 

### ISSUE THREAD

**Issue by jwdunne** [theseer/Autoload#94]
Is there any plans to support loading files with just functions in them? Or would you be open to a PR that added that as a feature? 

Context: 

This tools solves 50% of my problem flawlessly but...

I’m writing a PHP functional programming library. Naturally, I have a large number files containing just plain old functions and it’s tedious to keep updating composer files. 

I wanted a way to quickly generate an autoloader but everything only seems to work on classes (including this project). I have a few interfaces already (more on the way) and will have a number of traits and classes too so that works fine.

I could write my own tool that simply creates an includes file as a build artefact but not sure if PHP requires interfaces to be defined before they’re used in typehints. So I was looking at this tool and it does a great job with interfaces, and I’m assuming traits and classes. But, looking at the code, it doesn’t consider plain old functions.

The design decision makes sense given most high quality PHP projects use solid OO principles so I totally understand why it’s this way :)

**Comment by theseer** [comment]
PHP does not support autoloading for functions, so I don't see what an autoload generator can do here?

How would you trigger it? If you wrap the functions in a class and make all methods static, you could do `class::method()`. Given it's a class, you'd have autoloading again.

**Comment by theseer** [comment]
I don't think there's anything to be done here.

**Comment by jwdunne** [comment]
Actually, I was looking at the code and thinking that, upon detection of a function, it adds the file to a set of files that contain functions. 

Using that set, it compiles a static list of requires that have exported constants and functions in them, which is appended to the end of the auto load file, after whatever is done for classes, interfaces and traits (depending on whether static is set).

**Comment by theseer** [comment]
hmm... Still trying to see the use case here.

I'm also wondering how stable the result would be, keeping in mind that, in many cases, files that define global functions do more than just that: They contain directly executable code.

You'd also have to topologically sort the requires in case functions are called in these directly executable lines of code as they may require other functions to be loaded before that to work. Same goes for constant definitions, as `define` can be used with a function (e.g. `define('foo', (function(){return 'bar';})());`).  So you'd also have to actually parse the code for function calls.

Could of course be done. But what's different from having a regular bootstrap script that loads the generated autoloader file and whatever list of files you need to get the functions in? Why would it be added *to* the autoloader file?

I'm not trying to avoid adding features to `phpab`. It's a lot of work to create something that has a chance of being stable. Not sure if it's worth the effort, particularly given that I consider that a very undesirable way of creating software ;)

**Comment by jwdunne** [comment]
Hrm, the same could be said for classes. There are projects that do that too. It’d be daft to expect a tool to support generating a list of requires that are required by function calls. But I see what you mean.

I’m writing a library that defines lots of pure functions. I wasn’t thinking about side effects at all - including any file in my project has only the effect of defining functions, constants (I.e callable constants) and other symbols. Never side effects. 

I was simply looking for a solution where I’m not having to list all of my files in composer to generate an autoloader, instead listing just one, generated file as part of the build. A quick script that recurses my source folder does the trick. I was simply wondering if a tool that generated the same for interfaces/classes did the same for functions too, recognising that only requires need to be generated.
