### ISSUE TITLE
Can't generate autoloader for nikic/php-parser

### ISSUE THREAD

**Issue by remicollet** [theseer/Autoload#96]
```
phpab 1.25.9 - Copyright (C) 2009 - 2020 by Arne Blankerts and Contributors

Scanning directory lib/PhpParser
Could not process file '/dev/shm/BUILD/PHP-Parser-1c13d05035deff45f1230ca68bd7d74d621762d9/lib/PhpParser/Error.php' due to parse errors: Parse error while trying to process class definition (unexpected token in name).

```

This only happens with PHP 7.3, ok with PHP 7.4

**Comment by remicollet** [comment]
Nah... php 8.0 was badly enable during the build

**Comment by theseer** [comment]
The master branch should also work with PHP 8.0.

I'll be releasing a new version of it soon, still pondering whether or not I want to still test things with 7.1 and older. Currently, it's tested on 7.2+ but should ( :-/ ) work with 5.6 as advertised..
